export const items =  [
    {
      id: 1,
      category: 'mobiles',
      title: "Apple iPhone 15",
      img: 'images/iphone 15.jpg',
      amazonLink: 'https://amzn.to/3PuckZp',
      description: 'Apple iPhone 15 ',
      price: '$499.00',
    },
    {
      id: 5,
      category: 'laptops',
      title: "Asus Rog Zephyrys Z14",
      img: 'images/rog zephyrus.jpeg',
      amazonLink: 'https://amzn.to/3EzeQaC',
      description: 'Best Gaming Laptop... ',
      price: '$599.00',
    },
    {
      id: 7,
      category: 'tablets',
      title: "Xiaomi Pad 6",
      img: 'images/s tab.jpeg',
      amazonLink: 'https://amzn.to/3ZeNRdY',
      description: 'Xiaomi Pad 6 ',
      price: '$199.00',
    },
    {
      id: 2,
      category: 'mobiles',
      title: "Asus Rog 7",
      img: 'images/rog 7.jpg',
      amazonLink: 'https://amzn.to/44MiYi6',
      description: 'Best Gaming Phone',
      price: '$399.00',
    },
    {
      id: 6,
      category: 'tablets',
      title: "Lenovo Tab P12 Pro",
      img: 'images/L tab.jpeg',
      amazonLink: 'https://amzn.to/3RabsdH',
      description: 'Lenovo Tab P12 ',
      price: '$199.00',
    },
    {
      id: 3,
      category: 'mobiles',
      title: "Asus Rog 8",
      img: 'images/rog 8.jpeg',
      amazonLink: 'https://amzn.to/3r6XJtv',
      description: 'Asus Best Phone',
      price: '$299.00',
    },
    {
      id: 4,
      category: 'laptops',
      title: "Asus Tuf 9",
      img: 'images/asus tuf.jpeg',
      amazonLink: 'https://amzn.to/44JsK4r',
      description: 'Asus Tuf 9 ',
      price: '$499.00',
    },
    {
      id: 9,
      category: 'tablets',
      title: "Samsung Galaxy Tab A8",
      img: 'images/s tab.jpeg',
      amazonLink: 'https://amzn.to/3Pdsh4F',
      description: 'Samsung Galaxy Tab ',
      price: '$159.00',
    },
    {
      id: 8,
      category: 'laptops',
      title: "Apple MacBook Air",
      img: 'images/macbook.jpeg',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'Apple MacBook Air ',
      price: '$359.00',
    },


  ]